 
<link rel="stylesheet" type="text/css" href="http://localhost/multishopping/public/table_style_plugin/SyntaxHighlighter.css" />

<script type="text/javascript" src="http://localhost/multishopping/public/table_style_plugin/jquery.js"></script>

<script type="text/javascript" src="http://localhost/multishopping/public/table_style_plugin/styletable.jquery.plugin.js"></script>

<script type="text/javascript">

    $(function() {

        $('table#table1').styleTable();
        
        $('table#table2').styleTable({
            th_bgcolor: '#3E83C9',
            th_color: '#ffffff',
            th_border_color: '#333333',
            tr_odd_bgcolor: '#ECF6FC',
            tr_even_bgcolor: '#ffffff',
            tr_border_color: '#95BCE2',
            tr_hover_bgcolor: '#BCD4EC'

        });

    });

</script>
<h1>Datos del usuario</h1>
<a href="<?php echo $this->basePath() ?>/admin/proveedores/registrar">nuevo</a>
<table width="472" height="72"  id="table2" style="width:500px; text-align:left">
    <tr>
        <th>Id</th>
        <th>Correo</th>
        <th>Telefono</th>
        <th>E-Mail</th>
        <th>Eliminar</th>
        <th> </th>
    </tr>
    <?php foreach ($this->datos as $dato) { ?>
        <tr style="background-color:<?php echo $this->cycle(array("#F0F0F0", "#FFFFFF"))->next() ?>">
            <td><?php echo $dato["id_proveedores"] ?></td>
            <td><?php echo $dato["comercial"] ?></td>
            <td><?php echo $dato["telefono"] ?> </td>
            <td>&nbsp; </td>
            <td><a href="<?php echo $this->basePath() ?>/admin/proveedores/eliminar/<?php echo $dato['id_proveedores'] ?>"><img src="../../../../../public/img/eliminar.png" width="16" height="16" />eliminar</a> </td>
            <td><a href="<?php echo $this->basePath() ?>/admin/index/ver/<?php echo $dato["id"] ?>">ver</a> </td>
        </tr>
    <?php } ?>
    <?php
    $this->cycle()->assign(array("#F0F0F0", "#FFFFFF"));
    $this->cycle()->prev();
    ?>
</table>
