<h1>Registrar Propveedores</h1>
<?php
$form = $this->form;
$form->prepare();


$form->setAttributes(array(
    'action' => $this->url . '/admin/proveedores/registrar',
    'method' => 'post'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');

// Render the opening tag
echo $this->form()->openTag($form);
?>

<?php
if (!empty($this->id_proveedores)) {
    ?>
    <p style="color: green;">El registro se ingreso correctamente</p>
    <?php
}
?>

<div class="form_element">
    <?php
    $name = $form->get('comercial');
    echo $formLabel->openTag() . $name->getOption('label') . " ";

    //echo $this->formElementErrors($name);
    echo $formLabel->closeTag();
    echo $this->formInput($name);
    ?>
</div>
<div class="form_element">
    <?php
    $name = $form->get('telefono');
    echo $formLabel->openTag() . $name->getOption('label') . " ";

    //echo $this->formElementErrors($name);
    echo $formLabel->closeTag();
    echo $this->formInput($name);
    ?>
</div>
<div class="form_element">
    <?php
    $name = $form->get('nombre');
    echo $formLabel->openTag() . $name->getOption('label') . " ";

    //echo $this->formElementErrors($name);
    echo $formLabel->closeTag();
    echo $this->formInput($name);
    ?>
</div>
<?php echo $this->formElement($form->get('guardar')) ?>
<?php echo $this->form()->closeTag() ?>