<h1>Registrar Proveedores</h1>
<?php
$form = $this->form;
$form->prepare();


$form->setAttributes(array(
    'action' => $this->url . '/admin/proveedores/registrar',
    'method' => 'post'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');

// Render the opening tag
echo $this->form()->openTag($form);
?>

<?php
if (!empty($this->id_proveedores)) {
    ?>
    <p style="color: green;">El registro se ingreso correctamente</p>
    <p>
        <?php
    }
    ?>
</p>
 
<table width="40%" border="0" cellspacing="1" cellpadding="1">
    <tr>
        <th width="15" scope="col">&nbsp;</th>
        <th width="105" scope="col">
    <div class="form_element">
            <div align="left">
              <?php
            $name = $form->get('comercial');
            echo $formLabel->openTag() . $name->getOption('label') . " ";

            //echo $this->formElementErrors($name);
            echo $formLabel->closeTag();
            echo $this->formInput($name);
            ?>
                </div>
    </div></th>
        <th width="105" scope="col">&nbsp;</th>
        <td><div class="form_element">
            <?php
            $name = $form->get('apellido_p');
            echo $formLabel->openTag() . $name->getOption('label') . " ";

            //echo $this->formElementErrors($name);
            echo $formLabel->closeTag();
            echo $this->formInput($name);
            ?>
        </div></td>
  </tr>
<tr>
    <th scope="row">&nbsp;</th>
    <td>
        <div class="form_element">
            <?php
            $name = $form->get('telefono');
            echo $formLabel->openTag() . $name->getOption('label') . " ";

            //echo $this->formElementErrors($name);
            echo $formLabel->closeTag();
            echo $this->formInput($name);
            ?>
        </div>    </td>
    <td>&nbsp;</td>
    <td><div class="form_element">
        <?php
            $name = $form->get('apellido_m');
            echo $formLabel->openTag() . $name->getOption('label') . " ";

            //echo $this->formElementErrors($name);
            echo $formLabel->closeTag();
            echo $this->formInput($name);
            ?>
    </div></td>
</tr>
<tr>
    <th scope="row">&nbsp;</th>
    <td>
        <div class="form_element">
            <?php
            $name = $form->get('nombre');
            echo $formLabel->openTag() . $name->getOption('label') . " ";

            //echo $this->formElementErrors($name);
            echo $formLabel->closeTag();
            echo $this->formInput($name);
            ?>
        </div>    </td>
    <td>&nbsp;</td>
    <td><div class="form_element">
        <?php
            $name = $form->get('direccion');
            echo $formLabel->openTag() . $name->getOption('label') . " ";

            //echo $this->formElementErrors($name);
            echo $formLabel->closeTag();
            echo $this->formInput($name);
            ?>
    </div></td>
</tr>
<tr>
    <th scope="row">&nbsp;</th>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
</tr>
</table>
 

<?php echo $this->formElement($form->get('guardar')) ?>
<?php echo $this->form()->closeTag() ?>